apiVersion: v1
kind: Service
metadata:
  name: user-management-backend-service
spec:
  selector:
    app: user-management-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP