apiVersion: v1
kind: Service
metadata:
  name: user-management-frontend-service
spec:
  selector:
    app: user-management-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: ClusterIP