name: CI/CD pipeline
run-name: Build and Release Automation
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Github-Actions-project
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if secret exists
        run: |
          if [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Docker password secret is set"
          else
            echo "Docker password secret is not set"
            exit 1
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sumanjeet0012
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t sumanjeet0012/build_and_release_automation:${{ github.sha }} .
          docker tag sumanjeet0012/build_and_release_automation:${{ github.sha }} sumanjeet0012/build_and_release_automation:latest
          docker push sumanjeet0012/build_and_release_automation:${{ github.sha }}
      - name: push to docker hub
        run: |
          docker push sumanjeet0012/build_and_release_automation:${{ github.sha }}
          docker push sumanjeet0012/build_and_release_automation:latest
      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@v0.29.0
        with:
          image-ref: sumanjeet0012/build_and_release_automation:${{ github.sha }}