name: CI/CD pipeline
run-name: Build and Release Automation
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Github-Actions-project
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if secret exists
        run: |
          if [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Docker password secret is set"
          else
            echo "Docker password secret is not set"
            exit 1
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sumanjeet0012
          password: ${{ secrets.DOCKER_PASSWORD }}

